puts "Hello Ruby!"
#puts "This should be interesting"
#puts "Jimmy's gonna love what I'm doing!"
#puts "He'd be so proud"
#puts "It'd help if he existed, though"
#puts "Instead, he's a figment of my imagination"
#puts "So it goes, I guess."